{% set name = "typing_inspect" %}
{% set version = "0.9.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b23fc42ff6f6ef6954e4852c1fb512cdd18dbea03134f91f856a95ccc9461f78

build:
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - mypy_extensions >=0.3.0
    - python >={{ python_min }}
    - typing_extensions >=3.7.4

test:
  imports:
    - typing_inspect
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: http://github.com/ilevkivskyi/typing_inspect
  license: MIT
  license_file: LICENSE
  summary: Runtime inspection utilities for typing module.

extra:
  recipe-maintainers:
    - tarcisioe
    - thewchan
