{% set name = "typing_inspect" %}
{% set version = "0.7.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 047d4097d9b17f46531bf6f014356111a1b6fb821a24fe7ac909853ca2a782aa

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python
    - mypy_extensions >=0.3.0
    - typing_extensions >=3.7.4

test:
  imports:
    - typing_inspect

about:
  home: http://github.com/ilevkivskyi/typing_inspect
  license: MIT
  license_file: LICENSE
  summary: The “typing_inspect” module defines experimental API for runtime inspection of types defined in the standard “typing” module.

extra:
  recipe-maintainers:
    - tarcisioe
