{% set name = "typing_inspect" %}
{% set version = "0.8.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8b1ff0c400943b6145df8119c41c244ca8207f1f10c9c057aeed1560e4806e3d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv
  noarch: python

requirements:
  host:
    - python
    - pip
  run:
    - python >=3.3
    - mypy_extensions >=0.3.0
    - typing_extensions >=3.7.4

test:
  imports:
    - typing_inspect

about:
  home: http://github.com/ilevkivskyi/typing_inspect
  license: MIT
  license_file: LICENSE
  summary: The “typing_inspect” module defines experimental API for runtime inspection of types defined in the standard “typing” module.

extra:
  recipe-maintainers:
    - tarcisioe
